version: "3"

tasks:
  build:
    desc: Build the app
    cmds:
      - GOFLAGS=-mod=mod go build -o bin/mood-radio-discord-bot main.go

  run:
    desc: Run the app
    cmds:
      - GOFLAGS=-mod=mod go run main.go -t $BOT_TOKEN

  bot:
    desc: Execute the bot
    cmds:
      - ./bin/mood-radio-discord-bot -t $BOT_TOKEN
